[tox]
env_list = py312,mypy,doc
skip_missing_interpreters = true

[testenv]
description = Run pytest tests
extras = test
commands_pre = pip install --force-reinstall --no-deps cmd2_ext_test
commands = pytest

[testenv:mypy]
description = Run mypy type checker
commands = mypy -p showtime

[testenv:doc]
description = Check docstring coverage
skip_install = true
deps = interrogate>=1.5
commands = interrogate --quiet --fail-under 80 showtime
